const navItems = [
  { name: "Home", href: "/" },
  { name: "About Us", href: "/about" },
  { name: "Services", href: "/services" },
  { name: "Products", href: "/products" },
  { name: "Projects & Testimonies", href: "/project-and-testimonies" },
  { name: "Contact Us", href: "/contacts" },
];

const generators = [
  {
    name: "PGS-1-15-F",
    slug: "pgs-1-15-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "15 kVA / 12 kW",
    primePower: "13 kVA / 11 kW",
    engine: "FAW 4DWB1-3RD",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "12V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "220 x 95 x 125 cm",
    weight: "N/A",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Turbo Charged",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102mm x 115mm",
      compression: "N/A",
      displacement: "3.8 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology Brushless",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN 6110U Genset Digital Control",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Small industrial plants",
      "Retail establishments",
      "Medical clinics",
      "Residential complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "A compact 15 kVA diesel generator set with silent enclosure, featuring SMARTGEN 6110U digital control and turbo-charged engine. Ideal for small businesses, residential complexes, and emergency backup power applications.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-25-F",
    slug: "pgs-1-25-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "25 kVA / 20 kW",
    primePower: "22 kVA / 18 kW",
    engine: "FAN/DE 4DW91-38D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "225 x 95 x 125 cm",
    weight: "810 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "90x100",
      compression: "17:1",
      displacement: "2.54 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Small to medium industrial plants",
      "Office buildings",
      "Medical facilities",
      "Commercial complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water pumping stations",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "25 kVA diesel generator with natural aspiration engine and comprehensive protection systems. Perfect for small to medium commercial applications requiring reliable backup power.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-35-F",
    slug: "pgs-1-35-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "35 kVA / 28 kW",
    primePower: "31 kVA / 25 kW",
    engine: "FAN/DE 4DW92-42D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "230 x 95 x 125 cm",
    weight: "870 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "90x100",
      compression: "17:1",
      displacement: "2.54 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Medium industrial plants",
      "Hospital backup power",
      "Commercial buildings",
      "Educational institutions",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment facilities",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "35 kVA silent diesel generator set designed for medium-scale power requirements. Features advanced control systems and robust construction for continuous operation.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-50-F",
    slug: "pgs-1-50-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "50 kVA / 40 kW",
    primePower: "45 kVA / 36 kW",
    engine: "FAN/DE 4DX21-61D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 135 cm",
    weight: "870 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Medium industrial plants",
      "Data centers",
      "Hospitals",
      "Commercial complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "50 kVA diesel generator with 3.86L engine capacity, providing reliable power for medium to large commercial and industrial applications.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-60-F",
    slug: "pgs-1-60-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "60 kVA / 48 kW",
    primePower: "54 kVA / 53 kW",
    engine: "FAN/DE 40X22-75D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 135 cm",
    weight: "870 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Medium to large industrial plants",
      "Data centers",
      "Hospitals",
      "Commercial buildings",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "60 kVA power generator with robust 3.86L engine, designed for continuous operation in demanding industrial environments.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-75-F",
    slug: "pgs-1-75-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "75 kVA / 60 kW",
    primePower: "69 kVA / 55 kW",
    engine: "FAN/DE 4DX23-90D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "255 x 105 x 135 cm",
    weight: "900 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers",
      "Hospitals",
      "Commercial complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "75 kVA heavy-duty diesel generator with enhanced power output for large commercial and industrial applications requiring uninterrupted power supply.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-100-F",
    slug: "pgs-1-100-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "100 kVA / 80 kW",
    primePower: "90 kVA / 72 kW",
    engine: "FAN/DE 6A4DF2-14D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "255 x 105 x 135 cm",
    weight: "900 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers and server rooms",
      "Hospitals and healthcare facilities",
      "Commercial buildings and complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "100 kVA industrial-grade diesel generator set with advanced control systems, designed for critical power applications in data centers and healthcare facilities.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-125-F",
    slug: "pgs-1-125-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "125 kVA / 100 kW",
    primePower: "112 kVA / 90 kW",
    engine: "FAN/DE CABDF2D-16D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "255 x 105 x 135 cm",
    weight: "900 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers and server rooms",
      "Hospitals and healthcare facilities",
      "Commercial buildings and complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "125 kVA high-capacity diesel generator with premium components, engineered for continuous operation in mission-critical environments.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-150-F",
    slug: "pgs-1-150-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "150 kVA / 120 kW",
    primePower: "135 kVA / 108 kW",
    engine: "FAN/DE CABDF2D-21D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "330 x 120 x 200 cm",
    weight: "1200 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers and server rooms",
      "Hospitals and healthcare facilities",
      "Commercial buildings and complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "150 kVA industrial diesel generator set with robust construction and advanced control systems, designed for heavy-duty applications and continuous operation.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-175-F",
    slug: "pgs-1-175-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "175 kVA / 140 kW",
    primePower: "160 kVA / 128 kW",
    engine: "FAN/DE CABDF2D-21D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "330 x 120 x 200 cm",
    weight: "1200 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers and server rooms",
      "Hospitals and healthcare facilities",
      "Commercial buildings and complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "175 kVA high-performance diesel generator with enhanced power output, ideal for large-scale industrial operations and critical infrastructure.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-200-F",
    slug: "pgs-1-200-f",
    category: "faw-diesel",
    images: [
      "/images/faw1.webp",
      "/images/faw2.webp",
      "/images/faw3.webp",
      "/images/faw4.webp",
    ],
    standbyPower: "200 kVA / 165 kW",
    primePower: "188 kVA / 150 kW",
    engine: "FAN/DE CABD-L-27D",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 380V/220V, 440V/254V, 480V/277V",
    dimensions: "300 x 120 x 200 cm",
    weight: "1200 kg",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",

    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Natural aspiration",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102x118",
      compression: "17:1",
      displacement: "3.86 L",
    },

    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },

    features: [
      "SMARTGEN Genset Digital Control with Auto/Manual Start",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],

    applications: [
      "Large industrial plants",
      "Data centers and server rooms",
      "Hospitals and healthcare facilities",
      "Commercial buildings and complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Water treatment plants",
    ],

    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },

    description:
      "200 kVA premium diesel generator set, the flagship model in our lineup, designed for the most demanding industrial applications and continuous heavy-duty operation.",

    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },

  // Cummins Generators
  {
    name: "PGS-1-125-C",
    slug: "pgs-1-125-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "125 kVA / 100 kW",
    primePower: "112 kVA / 90 kW",
    engine: "Cummins 6BT5S-62",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 125 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "6 inline",
      aspiration: "Turbo-charged",
      cycle: "6",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "17.3:1",
      displacement: "5.9 L",
    },
    alternatorSpecs: {
      technology: "Standard Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Small industrial plants",
      "Retail establishments",
      "Medical clinics",
      "Residential complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 125 kVA diesel generator set with silent enclosure, featuring DEEP SEA ELECTRONICS control module and turbo-charged Cummins engine. Suitable for various industrial and commercial backup power applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-150-C",
    slug: "pgs-1-150-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "150 kVA / 120 kW",
    primePower: "112 kVA / 90 kW",
    engine: "Cummins 6BT5S-62",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "295 x 165 x 110 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "6 inline",
      aspiration: "Turbo-charged",
      cycle: "6",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "17.3:1",
      displacement: "5.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Medium industrial plants",
      "Commercial buildings",
      "Hospitals",
      "Large residential complexes",
      "Construction sites",
      "Data centers",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 150 kVA diesel generator set with silent enclosure, featuring Stamford alternator technology and turbo-charged Cummins engine. Ideal for medium-scale commercial and industrial backup power needs.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-175-C",
    slug: "pgs-1-175-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "175 kVA / 140 kW",
    primePower: "157 kVA / 126 kW",
    engine: "Cummins 6BTAAS 9-G12",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "310 x 175 x 110 cm",
    weight: "1200 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "6 inline",
      aspiration: "Turbo-charged",
      cycle: "6",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "17.3:1",
      displacement: "5.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Large industrial plants",
      "Commercial complexes",
      "Hospitals",
      "Data centers",
      "Construction sites",
      "Telecommunications infrastructure",
      "Municipal buildings",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 175 kVA diesel generator set with silent enclosure, featuring advanced Cummins engine and Stamford alternator technology. Suitable for large-scale commercial and industrial backup power applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-25-C",
    slug: "pgs-1-25-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "25 kVA / 20 kW",
    primePower: "22 kVA / 18 kW",
    engine: "Cummins 453.9 G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "225 x 95 x 125 cm",
    weight: "780 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Naturally Aspirated",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Small retail shops",
      "Medical clinics",
      "Residential backup",
      "Small offices",
      "Construction sites",
      "Telecommunications",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A compact 25 kVA diesel generator set with silent enclosure, featuring naturally aspirated Cummins engine and reliable Stamford alternator. Ideal for small businesses and residential backup power.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-200-C",
    slug: "pgs-1-200-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "200 kVA / 165 kW",
    primePower: "190 kVA / 150 kW",
    engine: "Cummins 6CTA8.3-G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "310 x 175 x 110 cm",
    weight: "1200 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "6 inline",
      aspiration: "Turbo-charged",
      cycle: "6",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "114×135",
      compression: "17.3:1",
      displacement: "6.3 L",
    },
    alternatorSpecs: {
      technology: "Standard Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Large industrial plants",
      "Commercial complexes",
      "Hospitals",
      "Data centers",
      "Construction sites",
      "Telecommunications infrastructure",
      "Municipal buildings",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A powerful 200 kVA diesel generator set with silent enclosure, featuring large displacement Cummins engine and robust alternator technology. Designed for heavy-duty industrial and commercial backup power applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-35-C",
    slug: "pgs-1-35-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "35 kVA / 28 kW",
    primePower: "31 kVA / 25 kW",
    engine: "Cummins 453.9 G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "225 x 95 x 125 cm",
    weight: "780 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Naturally Aspirated",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Small retail shops",
      "Medical clinics",
      "Residential backup",
      "Small offices",
      "Construction sites",
      "Telecommunications",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A compact 35 kVA diesel generator set with silent enclosure, featuring naturally aspirated Cummins engine and reliable Stamford alternator. Ideal for small businesses and residential backup power.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-50-C",
    slug: "pgs-1-50-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "50 kVA / 40 kW",
    primePower: "45 kVA / 36 kW",
    engine: "Cummins 4BT8.9-G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 125 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Turbo-charged",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Medium retail establishments",
      "Medical clinics",
      "Residential complexes",
      "Small offices",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 50 kVA diesel generator set with silent enclosure, featuring turbo-charged Cummins engine and Stamford alternator technology. Suitable for medium-scale commercial and residential backup power applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-60-C",
    slug: "pgs-1-60-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "60 kVA / 48 kW",
    primePower: "54 kVA / 53 kW",
    engine: "Cummins 4BTAS 9 G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 125 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Turbo-charged",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Stamford Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Medium industrial plants",
      "Commercial buildings",
      "Medical facilities",
      "Residential complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 60 kVA diesel generator set with silent enclosure, featuring turbo-charged Cummins engine and Stamford alternator technology. Designed for reliable backup power in commercial and industrial applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-75-C",
    slug: "pgs-1-75-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "75 kVA / 60 kW",
    primePower: "69 kVA / 55 kW",
    engine: "Cummins 4BTAS.9 G2",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 125 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Turbo-charged",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Standard Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Medium industrial plants",
      "Commercial buildings",
      "Medical facilities",
      "Large residential complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 75 kVA diesel generator set with silent enclosure, featuring turbo-charged Cummins engine and reliable alternator technology. Suitable for medium-scale commercial and industrial backup power needs.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
  {
    name: "PGS-1-100-C",
    slug: "pgs-1-100-c",
    category: "cummins-diesel",
    images: [
      "/images/cummins1.webp",
      "/images/cummins2.webp",
      "/images/cummins3.webp",
      "/images/cummins4.webp",
    ],
    standbyPower: "100 kVA / 80 kW",
    primePower: "90 kVA / 72 kW",
    engine: "Cummins 4BTAS® G11",
    speed: "1800 rpm",
    frequency: "60 Hz",
    fuelType: "Diesel",
    startingVoltage: "24V",
    voltageOptions:
      "208V/120V, 220V/127V, 240V/139V, 360V/220V, 440V/254V, 480V/277V",
    dimensions: "235 x 95 x 125 cm",
    weight: "980 Kgs",
    fuelCapacity: "Good for 8 Hours",
    connectionMode: "2/ Single Phase",
    speedControl: "Electronically",
    type: "Silent",
    engineSpecs: {
      cylinders: "4 inline",
      aspiration: "Turbo-charged",
      cycle: "4",
      combustion: "Direct Injection",
      cooling: "Water Cooled",
      boreStroke: "102×120",
      compression: "16.5:1",
      displacement: "3.9 L",
    },
    alternatorSpecs: {
      technology: "Standard Technology",
      insulation: "Class H",
      excitation: "Self-Excitation or PMG",
      protection: "IP23",
    },
    features: [
      "DEEP SEA ELECTRONICS Auto Start Control Module",
      "Sound Proof / Weather Proof Steel enclosure",
      "Automatic Battery Charger with two-stage charging",
      "Emergency push stop button",
      "Large residential muffler for silent operation",
      "SWG Genset Starting Battery with Nano-Technology",
      "Mobile trailer option available",
    ],
    applications: [
      "Medium industrial plants",
      "Commercial complexes",
      "Hospitals",
      "Large residential complexes",
      "Construction sites",
      "Telecommunications infrastructure",
      "Agricultural applications",
    ],
    certifications: {
      engine: "ISO 3046, BS 5514, DIN 6271",
      alternator:
        "UTE NFC 51-111-105-110 ICE34-1, BS 5000-4999 NEMA MG 21, VDE 0530 ISO 8528",
    },
    description:
      "A 100 kVA diesel generator set with silent enclosure, featuring turbo-charged Cummins engine and reliable alternator technology. Ideal for medium to large-scale commercial and industrial backup power applications.",
    operationConditions: {
      altitude: "Up to 1500m",
      temperature: "Up to 40°C",
      derating: "1% per 100m above 1500m",
    },
  },
];

export { navItems, generators };
